
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end

use_frameworks!
inhibit_all_warnings!

platform :ios, '8.0'

target 'MKSensor_Example' do
  pod 'MKSensor', :path => '../'
  pod 'Masonry'
  pod 'FMDB'
  pod 'Toast'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'HJTabViewController',     :git => 'https://github.com/panghaijiao/HJTabViewController.git'
  pod 'YYKit'
  pod 'MLInputDodger'
  pod 'FLAnimatedImage'
  pod 'AFNetworking'
  pod 'CircleProgressBar'
  
end
